repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
            - id: check-yaml
                exclude:.github/conda/meta.yaml|tests/cassettes/
            - id: end-of-file-fixer
            - id: trailing-whitespace
            - id: check-case-conflict
            - id: check-merge-conflict
    - repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: v0.3.0
        hooks:
            - id: ruff
            - id: ruff-format
    - repo: https://github.com/pappasam/toml-sort
        rev: v0.23.1
        hooks:
            - id: toml-sort-fix